version: '3.7'
services: 
  weatherapp_backend:
    container_name: weatherapp_backend
    environment: 
      - APPID=${APPID} 
    build:
      context: backend/
      dockerfile: Dockerfile
    ports: 
      - "9000:9000"
    command: npm run-script dev
    volumes: 
      - './backend:/app-be:rw'

  weatherapp_frontend:
    container_name: weatherapp_frontend
    environment: 
      - GEO_API_KEY=${GEO_API_KEY} 
    build: 
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    depends_on: 
      - weatherapp_backend
    volumes: 
      - './frontend:/app:rw'