version: '3'
services: 

  weatherapp_backend:
    container_name: weatherapp_backend
    build:
      context: backend/
      dockerfile: Dockerfile
    ports: 
      - "9000:9000"

  weatherapp_frontend:
    container_name: weatherapp_frontend
    environment: 
      - GEO_API_KEY=${GEO_API_KEY} 
    build: 
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on: 
      - weatherapp_backend
    # command: GEO_API_KEY=${GEO_API_KEY} npm start
    # command: npm start
    # command: npm start
    volumes: 
      - './frontend:/app:rw'
      - '/app/node_modules'