
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: weatherapp-backend
  labels:
    app: weather-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: weather-app
        tier: backend
    spec:
      containers:
      - name: weatherapp-backend
        image: gcr.io/[GCLOUD_PROJECT]/weatherapp_backend
        imagePullPolicy: Always
        ports:
          - containerPort: 9000
            protocol: TCP
        env:
          - name: APPID
            value: [APPID]